# Generated by Django 5.2.7 on 2025-10-03 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="分类名称")),
                (
                    "type",
                    models.CharField(
                        choices=[("income", "收入"), ("expense", "支出")],
                        max_length=10,
                        verbose_name="类型",
                    ),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="图标"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#1890ff", max_length=7, verbose_name="颜色"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="是否默认分类"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="organizations.organization",
                        verbose_name="所属组织",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "分类",
                "verbose_name_plural": "分类",
                "db_table": "categories",
                "ordering": ["order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "type"], name="categories_user_id_418e53_idx"
                    )
                ],
                "unique_together": {("user", "name", "type")},
            },
        ),
    ]
