# Generated by Django 5.2.7 on 2025-10-03 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_month", models.CharField(max_length=7, verbose_name="年月")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="预算金额"
                    ),
                ),
                (
                    "alert_threshold",
                    models.IntegerField(
                        default=80,
                        help_text="达到预算的百分比时预警",
                        verbose_name="预警阈值",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="categories.category",
                        verbose_name="分类",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "预算",
                "verbose_name_plural": "预算",
                "db_table": "budgets",
                "ordering": ["-year_month"],
                "indexes": [
                    models.Index(
                        fields=["user", "year_month"], name="budgets_user_id_5c8e4d_idx"
                    )
                ],
                "unique_together": {("user", "year_month", "category")},
            },
        ),
    ]
